# Generated by Django 5.1.2 on 2024-10-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_no',
            field=models.CharField(max_length=10),
        ),
    ]
