# Generated by Django 5.1.2 on 2024-10-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagment', '0002_alter_user_mobile_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=60)),
            ],
        ),
    ]
