# Generated by Django 5.1.2 on 2024-10-24 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagment', '0003_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='userid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='userManagment.user'),
        ),
    ]
