# Generated by Django 5.1.2 on 2024-11-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=60)),
            ],
        ),
    ]
